"""
services/tikz_exporter.py — ACADEMIC-QUALITY TIKZ EXPORT SYSTEM v2.0

DiagramSpec ob'ektini LaTeX TikZ kodiga o'tkazish.
Maqsad: Academic output, print-ready vector graphics, darslik sifati.

Xususiyatlari:
- RenderSpec → tikzpicture code
- Standalone LaTeX document option
- Export metadata (unsupported elements, warnings)
- Graceful fallback
- Academic style presets
"""

import time
import logging
import math
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass

from services.render_specs import (
    DiagramSpec, DiagramType, PointElement, SegmentElement, RayElement,
    LineElement, PolygonElement, TriangleElement, RectangleElement,
    SquareElement, CircleElement, ArcElement, AngleMarkerElement,
    PerpendicularElement, TickMarkElement, MidpointElement, ParallelElement,
    LabelElement, BoxElement, RoundedBoxElement, ArrowElement,
    FlowNodeElement, ChainNodeElement, GridCellElement,
    UnknownSymbolElement, StyleProfile, TikzExportResult
)

logger = logging.getLogger(__name__)


def latex_escape(text: str) -> str:
    """LaTeX-safe text escaping"""
    if not text:
        return ""
    replacements = {
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


TIKZ_PREAMBLE = r"""\documentclass[tikz, border=5mm]{standalone}
\usepackage{tikz}
\usetikzlibrary{calc, arrows.meta, positioning, decorations.markings}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[russian, english]{babel}
"""

class TikZExporter:
    """DiagramSpec -> LaTeX TikZ string converter"""
    
    def __init__(self, standalone: bool = False):
        self.indent = "  "
        self.standalone = standalone
        self._warnings: List[str] = []
        self._unsupported: List[str] = []
    
    def export(self, spec: DiagramSpec) -> TikzExportResult:
        """DiagramSpec ni TikZ kodiga o'tkazish — TikzExportResult qaytaradi"""
        start_time = time.time()
        self._warnings = []
        self._unsupported = []
        
        try:
            lines = []
            
            # Preamble comment
            lines.append("%% TikZ Export Generated by AI Math Bot")
            lines.append(f"%% Diagram Type: {spec.diagram_type.value}")
            lines.append(f"%% Signature: {spec.get_signature()}")
            lines.append("")
            
            # Start TikZ picture environment
            lines.append("\\begin{tikzpicture}[x=1cm, y=1cm, >=stealth]")
            
            # Global styles
            self._add_global_styles(lines, spec)
            
            # Render elements
            self._export_geometry(lines, spec)
            self._export_puzzles(lines, spec)
            
            # End TikZ picture environment
            lines.append("\\end{tikzpicture}")
            
            tikz_code = "\n".join(lines)
            
            full_doc = ""
            if self.standalone:
                full_doc = f"{TIKZ_PREAMBLE}\n\\begin{{document}}\n{tikz_code}\n\\end{{document}}\n"
            
            return TikzExportResult(
                success=True,
                tikz_code=tikz_code,
                full_document=full_doc,
                unsupported_elements=list(self._unsupported),
                warnings=list(self._warnings),
                export_time_ms=(time.time() - start_time) * 1000,
            )
        except Exception as e:
            logger.error(f"TikZ export error: {e}")
            return TikzExportResult(
                success=False,
                warnings=[str(e)],
                export_time_ms=(time.time() - start_time) * 1000,
            )
    
    def export_string(self, spec: DiagramSpec) -> str:
        """Backward compatibility: TikZ string qaytaradi"""
        result = self.export(spec)
        return result.tikz_code if result.success else f"%% Export Error"

    def _add_global_styles(self, lines: List[str], spec: DiagramSpec):
        """TikZ global uslublarini qo'shish"""
        profile = spec.style.style_profile
        l_width = spec.style.line_width * 0.4 # Scale for TikZ
        
        lines.append(f"{self.indent}\\tikzset{{")
        lines.append(f"{self.indent}{self.indent}every node/.style={{font=\\small}},")
        lines.append(f"{self.indent}{self.indent}main line/.style={{draw=black, line width={l_width}pt}},")
        
        if profile == StyleProfile.ACADEMIC:
            lines.append(f"{self.indent}{self.indent}box/.style={{draw=black, rounded corners=2pt, fill=white, inner sep=4pt}},")
        elif profile == StyleProfile.PRINT_FRIENDLY:
            lines.append(f"{self.indent}{self.indent}box/.style={{draw=black, fill=white, inner sep=3pt}},")
            
        lines.append(f"{self.indent}}}")
        lines.append("")

    def _export_geometry(self, lines: List[str], spec: DiagramSpec):
        """Geometrik elementlarni TikZ ga o'tkazish"""
        
        # Triangles
        for t in spec.triangles:
            v1, v2, v3 = t.v1, t.v2, t.v3
            fill = f", fill={t.fill_color}" if t.fill_color else ""
            lines.append(f"{self.indent}\\draw[main line{fill}] ({v1[0]:.2f}, {v1[1]:.2f}) -- ({v2[0]:.2f}, {v2[1]:.2f}) -- ({v3[0]:.2f}, {v3[1]:.2f}) -- cycle;")
            
            # Vertices labels
            for i, label in enumerate(t.labels):
                if label:
                    v = [v1, v2, v3][i]
                    cx, cy = (v1[0]+v2[0]+v3[0])/3, (v1[1]+v2[1]+v3[1])/3
                    angle = math.degrees(math.atan2(v[1]-cy, v[0]-cx))
                    lines.append(f"{self.indent}\\node at ({v[0]:.2f}, {v[1]:.2f}) [anchor={angle+180:.0f}] {{{label}}};")

        # Circles
        for c in spec.circles:
            fill = f", fill={c.fill_color}" if c.fill_color else ""
            lines.append(f"{self.indent}\\draw[main line{fill}] ({c.cx:.2f}, {c.cy:.2f}) circle ({c.radius:.2f});")
            if c.center_label:
                lines.append(f"{self.indent}\\fill ({c.cx:.2f}, {c.cy:.2f}) circle (1pt);")
                lines.append(f"{self.indent}\\node at ({c.cx:.2f}, {c.cy:.2f}) [below right] {{{c.center_label}}};")

        # Rectangles
        self._export_rectangles(lines, spec)
        
        # Segments
        for s in spec.segments:
            style = ", dashed" if s.style == "dashed" else ""
            lines.append(f"{self.indent}\\draw[main line{style}] ({s.x1:.2f}, {s.y1:.2f}) -- ({s.x2:.2f}, {s.y2:.2f});")
            if s.label:
                mx, my = (s.x1+s.x2)/2, (s.y1+s.y2)/2
                lines.append(f"{self.indent}\\node at ({mx:.2f}, {my:.2f}) [above] {{{s.label}}};")

        # Point elements
        for p in spec.points:
            lines.append(f"{self.indent}\\fill ({p.x:.2f}, {p.y:.2f}) circle (1.5pt);")
            if p.label:
                lines.append(f"{self.indent}\\node at ({p.x:.2f}, {p.y:.2f}) [anchor=south west] {{{p.label}}};")
        
        # Angle markers
        self._export_angle_markers(lines, spec)
        
        # Perpendiculars
        self._export_perpendiculars(lines, spec)
        
        # Tick marks
        self._export_tick_marks(lines, spec)
        
        # Midpoints
        self._export_midpoints(lines, spec)
        
        # Labels
        self._export_labels(lines, spec)

    def _export_puzzles(self, lines: List[str], spec: DiagramSpec):
        """Puzzle elementlarini TikZ ga o'tkazish"""
        
        # Boxes
        for b in spec.boxes:
            fill = f", fill={b.fill_color}" if b.fill_color else ""
            lines.append(f"{self.indent}\\draw[main line{fill}] ({b.x:.2f}, {b.y:.2f}) rectangle ({b.x+b.width:.2f}, {b.y+b.height:.2f});")
            if b.content:
                lines.append(f"{self.indent}\\node[font=\\small] at ({b.x+b.width/2:.2f}, {b.y+b.height/2:.2f}) {{{b.content}}};")
        
        # Rounded boxes
        self._export_rounded_boxes(lines, spec)

        # Arrows
        for a in spec.arrows:
            lines.append(f"{self.indent}\\draw[->, main line] ({a.x1:.2f}, {a.y1:.2f}) -- ({a.x2:.2f}, {a.y2:.2f});")
            if a.label:
                mx, my = (a.x1+a.x2)/2, (a.y1+a.y2)/2
                lines.append(f"{self.indent}\\node at ({mx:.2f}, {my:.2f}) [above] {{{a.label}}};")
        
        # Flow nodes
        self._export_flow_nodes(lines, spec)

        # Chain Nodes
        for i, cn in enumerate(spec.chain_nodes):
            lines.append(f"{self.indent}\\draw[main line] ({cn.x:.2f}, {cn.y:.2f}) circle (0.5cm) node {{{cn.content}}};")
            if i > 0:
                prev = spec.chain_nodes[i-1]
                lines.append(f"{self.indent}\\draw[->, main line] ({prev.x+0.5:.2f}, {prev.y:.2f}) -- ({cn.x-0.5:.2f}, {cn.y:.2f});")

        # Grid Cells
        for gc in spec.grid_cells:
            lines.append(f"{self.indent}\\node at ({gc.col:.2f}, {-gc.row:.2f}) [draw, minimum size=1cm] {{{gc.content}}};")

        # Unknown Symbols
        for us in spec.unknown_symbols:
            shape = "circle" if us.symbol_style == "circle" else "rectangle"
            lines.append(f"{self.indent}\\node[draw, {shape}, minimum size={us.size*2:.2f}cm, fill=yellow!20] at ({us.x:.2f}, {us.y:.2f}) {{{us.symbol}}};")
    
    def _export_angle_markers(self, lines: List[str], spec: DiagramSpec):
        """Burchak belgilarini TikZ ga o'tkazish"""
        for m in spec.angle_markers:
            v = m.vertex
            r1 = m.ray1
            r2 = m.ray2
            
            a1 = math.degrees(math.atan2(r1[1]-v[1], r1[0]-v[0]))
            a2 = math.degrees(math.atan2(r2[1]-v[1], r2[0]-v[0]))
            
            if a2 < a1:
                a2 += 360
            if a2 - a1 > 180:
                a1, a2 = a2, a1 + 360
            
            lines.append(f"{self.indent}\\draw ({v[0]:.2f}, {v[1]:.2f}) ++({a1:.1f}:{m.radius:.2f}) arc ({a1:.1f}:{a2:.1f}:{m.radius:.2f});")
            
            if m.label:
                mid = (a1 + a2) / 2
                lx = v[0] + (m.radius + m.label_offset + 0.15) * math.cos(math.radians(mid))
                ly = v[1] + (m.radius + m.label_offset + 0.15) * math.sin(math.radians(mid))
                lines.append(f"{self.indent}\\node[font=\\small\\itshape] at ({lx:.2f}, {ly:.2f}) {{{m.label}}};")
    
    def _export_perpendiculars(self, lines: List[str], spec: DiagramSpec):
        """Perpendikulyar belgilarini TikZ ga o'tkazish"""
        for p in spec.perpendiculars:
            v = p.vertex
            d1 = p.dir1
            d2 = p.dir2
            
            l1 = math.hypot(d1[0]-v[0], d1[1]-v[1])
            l2 = math.hypot(d2[0]-v[0], d2[1]-v[1])
            if l1 == 0 or l2 == 0:
                continue
            
            u1 = ((d1[0]-v[0])/l1, (d1[1]-v[1])/l1)
            u2 = ((d2[0]-v[0])/l2, (d2[1]-v[1])/l2)
            sz = p.size
            
            q1 = (v[0] + u1[0]*sz, v[1] + u1[1]*sz)
            q2 = (v[0] + u1[0]*sz + u2[0]*sz, v[1] + u1[1]*sz + u2[1]*sz)
            q3 = (v[0] + u2[0]*sz, v[1] + u2[1]*sz)
            
            lines.append(f"{self.indent}\\draw ({q1[0]:.2f}, {q1[1]:.2f}) -- ({q2[0]:.2f}, {q2[1]:.2f}) -- ({q3[0]:.2f}, {q3[1]:.2f});")
    
    def _export_tick_marks(self, lines: List[str], spec: DiagramSpec):
        """Tick mark belgilarini TikZ ga o'tkazish"""
        for t in spec.tick_marks:
            mx = (t.p1[0] + t.p2[0]) / 2
            my = (t.p1[1] + t.p2[1]) / 2
            dx = t.p2[0] - t.p1[0]
            dy = t.p2[1] - t.p1[1]
            length = math.hypot(dx, dy)
            if length == 0:
                continue
            nx, ny = -dy/length, dx/length
            sp = 0.08
            tl = t.length
            
            for i in range(t.count):
                off = (i - (t.count - 1) / 2) * sp
                tx = mx + dx/length * off
                ty = my + dy/length * off
                lines.append(f"{self.indent}\\draw ({tx-nx*tl/2:.2f}, {ty-ny*tl/2:.2f}) -- ({tx+nx*tl/2:.2f}, {ty+ny*tl/2:.2f});")
    
    def _export_midpoints(self, lines: List[str], spec: DiagramSpec):
        """O'rta nuqta belgilarini TikZ ga o'tkazish"""
        for m in spec.midpoints:
            mx = (m.p1[0] + m.p2[0]) / 2
            my = (m.p1[1] + m.p2[1]) / 2
            lines.append(f"{self.indent}\\fill ({mx:.2f}, {my:.2f}) circle (2pt);")
            if m.label:
                lines.append(f"{self.indent}\\node[font=\\small, below] at ({mx:.2f}, {my-0.15:.2f}) {{{m.label}}};")
    
    def _export_rectangles(self, lines: List[str], spec: DiagramSpec):
        """To'g'ri to'rtburchaklarni TikZ ga o'tkazish"""
        for r in spec.rectangles:
            fill = f", fill={r.fill_color}" if r.fill_color else ""
            lines.append(f"{self.indent}\\draw[main line{fill}] ({r.x:.2f}, {r.y:.2f}) rectangle ({r.x+r.width:.2f}, {r.y+r.height:.2f});")
            
            if r.show_diagonals:
                lines.append(f"{self.indent}\\draw[dashed] ({r.x:.2f}, {r.y:.2f}) -- ({r.x+r.width:.2f}, {r.y+r.height:.2f});")
    
    def _export_labels(self, lines: List[str], spec: DiagramSpec):
        """Label elementlarni TikZ ga o'tkazish"""
        for l in spec.labels:
            rot = f", rotate={l.rotation}" if l.rotation else ""
            lines.append(f"{self.indent}\\node[font=\\small{rot}] at ({l.x:.2f}, {l.y:.2f}) {{{l.text}}};")
    
    def _export_rounded_boxes(self, lines: List[str], spec: DiagramSpec):
        """Yumaloq qutilarni TikZ ga o'tkazish"""
        for b in spec.rounded_boxes:
            fill = f", fill={b.fill_color}" if b.fill_color else ""
            lines.append(f"{self.indent}\\draw[main line, rounded corners={b.radius:.2f}cm{fill}] ({b.x:.2f}, {b.y:.2f}) rectangle ({b.x+b.width:.2f}, {b.y+b.height:.2f});")
            if b.content:
                lines.append(f"{self.indent}\\node[font=\\small] at ({b.x+b.width/2:.2f}, {b.y+b.height/2:.2f}) {{{b.content}}};")
    
    def _export_flow_nodes(self, lines: List[str], spec: DiagramSpec):
        """Oqim tugunlarini TikZ ga o'tkazish"""
        for i, n in enumerate(spec.flow_nodes):
            lines.append(f"{self.indent}\\node[draw, rounded corners, minimum width=1.5cm, minimum height=0.8cm] (fn{i}) at ({n.x:.2f}, {n.y:.2f}) {{{n.content}}};")
            if i > 0:
                lines.append(f"{self.indent}\\draw[->, main line] (fn{i-1}) -- (fn{i});")

tikz_exporter = TikZExporter()
